### ISSUE TITLE
no file

### ISSUE THREAD

**Issue by cooper12121** [AlonEirew/cross-doc-event-coref#3]
excuse me,there is no wec.zip in datasets folder,where can i get it?

**Comment by AlonEirew** [comment]
Hi @gaoqiang-3416,

I've moved the files to huggingface hub, you can find them in the following link:
https://huggingface.co/datasets/biu-nlp/WEC-Eng

Let me know if this resolve the issue.

Thanks,
Alon.

**Comment by AlonEirew** [comment]
Closing as not active for a while..
